### ISSUE TITLE
Login연동 할 때 cors에러

### ISSUE THREAD

**Issue by k1k2brz** [TEAM-ACO/aco-front#24]
1. next.config.js에 아래의 코드 추가

async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: `http://localhost:15251/api/:path*`,
      },
    ];
  },

backendURL도 지우고 시도 해봤으나 CORS에러 해결 안됨.

2. package.json에 proxy 추가
"proxy": "http://localhost:15251" 해봤으나 안됨.

3. http-proxy-middleware 설치
setupProxy.js 만들고

const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = (app) => {
  app.use(
    createProxyMiddleware('/api', {
      target: 'http://localhost:15251/',
      changeOrigin: true,
    }),
  );
};
넣어봤으나 해결 안됨.

4. Next.js HTTP Proxy Middleware
사실상 1번 방법이라고 함.

그리고 가끔 됐나 싶을 때 431에러 (Header가 너무 길거나 용량초과 인듯)가 나서 안넘어가는 현상이 나타난다. (캐시도 지워봤는데 이게 문제가 아닌 것 같음)

path뒤에 *지우면 404에러가 뜸

**Comment by B-HS** [comment]
작동하는 파일 넣어놨어용 확신해주시고 안되면 또 댓글 주셔용 ㅠㅠ
